[package]
name = "dioxus-motion-transitions-macro"
version = "0.1.1"
edition = "2024"
description = "Page transition support for dioxus-motion"
license = "MIT"
authors = ["Sabin Regmi <get2sabin@gmail.com>"]
repository = "https://github.com/wheregmis/dioxus-motion"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.108", features = [
    "derive",
    "parsing",
    "proc-macro",
], default-features = false }
quote = { version = "1.0.41", default-features = false }
proc-macro2 = { version = "1.0.103", default-features = false }
